project:
  type: website

website:
  title: "TBEP Equity Strategy: Mapping"
  repo-url: https://github.com/tbep-tech/equity-plan-mapping
  page-footer:
    left: |
      Website created by Blake Simmons and Marcus Beck
    right: |
      This website was built with <a href="https://quarto.org/" target="_blank">Quarto</a>
  navbar:
    logo: tarpon.png
    left:
      - href: index.qmd
        text: Equity strategy overview
      - text: Methods
        menu:
          - href: ejscreen.qmd
            text: Getting demographic data
          - underserved.qmd
          - cejst.qmd
          - overburdened.qmd
          - example.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/tbep-tech/equity-plan-mapping
          - text: Report a Bug
            url:  https://github.com/tbep-tech/equity-plan-mapping/issues

format:
  html:
    theme: cosmo
    css: styles.css
    code-tools:
      source: repo

execute:
  echo: false
  warning: false
